### ISSUE TITLE
Add IPv6 Support

### ISSUE THREAD

**Issue by shepherdjay** [shepherdjay/ipfromwebpage#11]
Add an option to scrape and aggregate IPv6 addresses

**Comment by noahlvb** [comment]
Could you assign this issue to me, I'd like to work in it?

**Comment by shepherdjay** [comment]
Hey @noahlvb thanks for offering your help. Unfortunately I cant assign without giving you direct push access. But please feel free to make a pull request when you feel you have a working implementation and let me know if you need any assistance or if I can answer any questions

**Comment by noahlvb** [comment]
Oh I was not aware of that. I'll make a PR when I'am finished.
