### ISSUE TITLE
Package ipfromwebpage with an executable

### ISSUE THREAD

**Issue by shepherdjay** [shepherdjay/ipfromwebpage#9]
I want to make it easier to install and run ipfromwebpage via a pip installable.

**Comment by shepherdjay** [comment]
Initial package structure was converted to in pull #8 but not sure how to proceed as far as doing the following:

- Bumping version easy
- Making a global executable so someone only has to type ipfromwebpage

**Comment by chuckyz** [comment]
Do you want an executable (e.g.: like what pyinstaller or cx_freeze give you), or something on `PATH` so you can just `pip install ipfromwebpage` and then run `$ipfromwebpage [...]` ?

**Comment by shepherdjay** [comment]
Hey @chuckyz looking for something on PATH so the user experience can be straightforward
